language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install flake8
  - pip install .
script:
  - flake8 yaml_resume
  - python -m pytest --cov=yaml_resume tests/
after_success:
  - codecov
