language: python
dist: xenial
git:
  depth: false
env:
  matrix:
  - LINTER_CMD="black --check yaml_resume"
matrix:
  include:
  - python: 3.6
    before_install:
    - pip install black
  - python: 3.7
    before_install:
    - pip install black
  - python: 3.8
    before_install:
    - pip install black
  - python: pypy3
    env:
    - LINTER_CMD="echo 'Black not available on pypy'"
  allow_failures:
  - python: 3.8-dev
install:
- pip install -r requirements.txt
- pip install pytest-cov codecov
addons:
  sonarcloud:
    organization: notsag
    token:
      secure: WlHupxxuRgC34i+e+fLATfVfGneKg3HBLkMNlsT8Dsk5a8bYDYUh4hUPDJqVPk8hNoex2c+02KK0gtpuJ3pEfDEgxNhkFgfRZJqHv+bd/H0cESfPp6dECIY6UQUU61KF0bT+XaqtBZQ6WASYgL+3h0s08COPhkdGk71La7lSqN5iLVOre5S1fHUm0EEcMbrhVQI9G1iHl1Wg99FSpIt5iKqbrSJPQgqRVtMIihhvaiwYh9hLsXip45rMHek6LdelqPG3r+omMKuiGROIapYZQ2unTbEiU46kCkY380MYjhEUo1nUdK8+IrcCkJLlsttOtDpF1JPGRFUF4LpyuzuQw2x1exsymMFCIsggXPMa/ecDLYZwvtbCk72ntjEsF6awPZuIFsUk87R98tjcbZ41sK3upTLb2EvnntPwnUvo9Y2XVeZXFZEYll8cV0+aCFbNU1TBK3xbALpfA7Nd8DglTNhMxkRhcqU494wCDDQGA6ddIYFJJFZuOeIDBcofsnYDJY2CcQi5QK/p+xI4/WXuY+K/Vz1wlw9a0fO00BCkaY7sKVQpnd9PafFK8loElPZ3nL6yUN1AfZkdc8Vd57TTvfd63pUL5aKHIWCXm4l5xXCX4/sTIg8KgZzbyyka4DCxbagAL/lT36q6dJZgpMBUHi9k1OSj75JKRSZQqXdw41A=
script:
- "$LINTER_CMD"
- python -m pytest --cov=yaml_resume --cov-report xml:test-results/coverage.xml --junitxml=test-results/junit.xml
  tests/
- sonar-scanner
deploy:
  provider: pypi
  username: __token__
  password:
    secure: Papgp96picjFc244KI4hyBqY3wHNXCl11/1xWKHBHI3kxpajf4UGMwcAhs5iSX/mkwEAPepjehlmyvgJXnk3xTxsgO/0JrisULk+3DtPaEde6pSqUWSx9J7pCCKtH/XmSQktnIofbbENqZx0uTVK6IUUO+y1CjvUiq6ERSdMdOtJs6OYjemT0oimZ+ABvqSR6AzzZfMw6VEAPCjzFffblCxiYeoHCbu0qia2+S1H7+6BEclc/CJBzyrRVHFCZ8afiEi+Dy6sCpWYs+YDQ9vBteafaPYVJXx3QRMpXfMWA44atfJsvR3M44MEm7Kt/+TJWgeA32nw8ob4Nth/upROicY9qxeuk80CM3mHGgVV/eFNfIWHRZPvk013F88mGoJDOlMbbKGtEhCT5vXc0vn+TeN1nxkWtijbFpku2C7vvA4oNQkRZCrSwuq7vYCbUfxCMpz4DgBq7XroQL3twNA8oUsO0g6boXvROQGpdIn9L/FbatcuUc69EFdLcT4wb1cV6J+0Xs+X+DeG3envqJZJwn/BUeGSKDtT71aiTKiUeYrWyvw8P+VvGvdCHan7I3uTvojIV3TfhRysamutvtvn9++KP3kZWoSleAKsDiDa4Nfurd6LzLfKK71b3WhBQq8tBTRld93m8oZPhg6Sxe1iZLrpN53vxJJEU4f7sLn4BA4=
  on:
    tags: true
