language: python
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy3.5"
install:
  - pip install -r requirements.txt
  - pip install pytest-cov codecov flake8
script:
  - flake8 yaml_resume
  - python -m pytest --cov=yaml_resume tests/
after_success:
  - codecov
