language: python
dist: xenial
env:
  - LINTER_CMD="black --check yaml_resume"
matrix:
  include:
    - python: 3.5
      env:
        - LINTER_CMD="echo 'Black not available on Python3.5'"
    - python: 3.6
      before_install:
        - pip install black
    - python: 3.7
      before_install:
        - pip install black
    - python: 3.8-dev
      before_install:
        - pip install black
    - python: pypy3
      env:
        - LINTER_CMD="echo 'Black not available on pypy'"
  allow_failures:
    - python: 3.8-dev
install:
  - pip install -r requirements.txt
  - pip install pytest-cov codecov
script:
  - $LINTER_CMD
  - python -m pytest --cov=yaml_resume tests/
after_success:
  - codecov
